<?php
$allImages = [
    'img/alejandrobalde.png',
    'img/ansu_fati.png',
    'img/carvajal.png',
    'img/david_garcia.png',
    'img/david_raya.png',
    'img/fabian_ruiz.png',
    'img/fran_garcia.png',
    'img/gavi.png',
    'img/kepa.png',
    'img/laporte.png',
    'img/martin_zubimendi.png',
    'img/mikel_merino.png',
    'img/mikel_oyarzabal.png',
    'img/navas.png',
    'img/nico_williams.png',
    'img/oihan_sancet.png',
    'img/pau_torres.png',
    'img/rodrigo.png',
    'img/thumbnail_le_normand.png',
    'img/unai_simon.png',
]
?>